# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Machine Learning
email: guo675@purdue.com
description: >- # this means to ignore newlines until "baseurl:"
  ECE 595 / STAT 598 at Purdue University in Spring 2022
baseurl: "/ml1" # the subpath of your site, e.g. /blog
url: "qiguo.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  guoqi1123
domain: ml1.qiguo.org       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://ml1.qiguo.org  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /      # place folder name if the site is served in a subfolder

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html


# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs # uncomment for github build
# theme: just-the-docs # uncomment for local build
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
